language: java
sudo: required
dist: trusty

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/lib/
  - wget https://ci.kacperduras.pl/job/Skript/lastSuccessfulBuild/artifact/build/libs/Skript.jar --output-document $TRAVIS_BUILD_DIR/lib/Skript.jar

install: script/install
script: script/script

matrix:
  fast_finish: false
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk9
    - jdk: openjdk11
    - jdk: openjdk-ea

notifications:
  email: false
